#!/bin/bash
set -e
SCRIPTS=$(pwd)

TMPDIR=$(mktemp -d)
trap '{ cd ; rm -rf $TMPDIR; exit 255; }' SIGINT EXIT
cd "$TMPDIR"

for form in $("$SCRIPTS/list-forms"); do
  (
    git clone "git@github.com:rxnda/$form" "$TMPDIR/$form"
    cd "$TMPDIR/$form"
    git submodule update --init --recursive
    cd common
    ls
    git checkout master
    git pull --ff-only origin master
    cd ..
    git status
    git add common
    git commit -m "Upgrade build chain"
    git push origin master
  )
done
